import pyautogui as aut
usuario = input("Qual seu usuario do insta:")
senha = input("Qual sua senha do insta:")
#aut.mouseInfo()
aut.press("win")
aut.sleep(1)
aut.write("instagram")
aut.press("enter")
aut.sleep(2)
aut.moveTo(269,561)
aut.click()
aut.sleep(2)
aut.press("tab")
aut.write(f"{usuario}")
aut.sleep(2)
aut.moveTo(417,423)
aut.sleep(2)
aut.click()
aut.sleep(2)
aut.write(f"{senha}")
aut.sleep(2)
aut.moveTo(448,450)
aut.sleep(2)
aut.click()


